// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/v1/auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kaleabAlemayehu/protos/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceSendOTPProcedure is the fully-qualified name of the AuthService's SendOTP RPC.
	AuthServiceSendOTPProcedure = "/auth.v1.AuthService/SendOTP"
	// AuthServiceVerifyOTPProcedure is the fully-qualified name of the AuthService's VerifyOTP RPC.
	AuthServiceVerifyOTPProcedure = "/auth.v1.AuthService/VerifyOTP"
	// AuthServiceRegisterPINProcedure is the fully-qualified name of the AuthService's RegisterPIN RPC.
	AuthServiceRegisterPINProcedure = "/auth.v1.AuthService/RegisterPIN"
	// AuthServiceUnlockProcedure is the fully-qualified name of the AuthService's Unlock RPC.
	AuthServiceUnlockProcedure = "/auth.v1.AuthService/Unlock"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	authServiceServiceDescriptor           = v1.File_auth_v1_auth_proto.Services().ByName("AuthService")
	authServiceSendOTPMethodDescriptor     = authServiceServiceDescriptor.Methods().ByName("SendOTP")
	authServiceVerifyOTPMethodDescriptor   = authServiceServiceDescriptor.Methods().ByName("VerifyOTP")
	authServiceRegisterPINMethodDescriptor = authServiceServiceDescriptor.Methods().ByName("RegisterPIN")
	authServiceUnlockMethodDescriptor      = authServiceServiceDescriptor.Methods().ByName("Unlock")
)

// AuthServiceClient is a client for the auth.v1.AuthService service.
type AuthServiceClient interface {
	SendOTP(context.Context, *connect.Request[v1.SendOTPRequest]) (*connect.Response[v1.SendOTPResponse], error)
	VerifyOTP(context.Context, *connect.Request[v1.VerifyOTPRequest]) (*connect.Response[v1.VerifyOTPResponse], error)
	RegisterPIN(context.Context, *connect.Request[v1.RegisterPINRequest]) (*connect.Response[v1.RegisterPINResponse], error)
	Unlock(context.Context, *connect.Request[v1.UnlockRequest]) (*connect.Response[v1.UnlockResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		sendOTP: connect.NewClient[v1.SendOTPRequest, v1.SendOTPResponse](
			httpClient,
			baseURL+AuthServiceSendOTPProcedure,
			connect.WithSchema(authServiceSendOTPMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		verifyOTP: connect.NewClient[v1.VerifyOTPRequest, v1.VerifyOTPResponse](
			httpClient,
			baseURL+AuthServiceVerifyOTPProcedure,
			connect.WithSchema(authServiceVerifyOTPMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		registerPIN: connect.NewClient[v1.RegisterPINRequest, v1.RegisterPINResponse](
			httpClient,
			baseURL+AuthServiceRegisterPINProcedure,
			connect.WithSchema(authServiceRegisterPINMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		unlock: connect.NewClient[v1.UnlockRequest, v1.UnlockResponse](
			httpClient,
			baseURL+AuthServiceUnlockProcedure,
			connect.WithSchema(authServiceUnlockMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	sendOTP     *connect.Client[v1.SendOTPRequest, v1.SendOTPResponse]
	verifyOTP   *connect.Client[v1.VerifyOTPRequest, v1.VerifyOTPResponse]
	registerPIN *connect.Client[v1.RegisterPINRequest, v1.RegisterPINResponse]
	unlock      *connect.Client[v1.UnlockRequest, v1.UnlockResponse]
}

// SendOTP calls auth.v1.AuthService.SendOTP.
func (c *authServiceClient) SendOTP(ctx context.Context, req *connect.Request[v1.SendOTPRequest]) (*connect.Response[v1.SendOTPResponse], error) {
	return c.sendOTP.CallUnary(ctx, req)
}

// VerifyOTP calls auth.v1.AuthService.VerifyOTP.
func (c *authServiceClient) VerifyOTP(ctx context.Context, req *connect.Request[v1.VerifyOTPRequest]) (*connect.Response[v1.VerifyOTPResponse], error) {
	return c.verifyOTP.CallUnary(ctx, req)
}

// RegisterPIN calls auth.v1.AuthService.RegisterPIN.
func (c *authServiceClient) RegisterPIN(ctx context.Context, req *connect.Request[v1.RegisterPINRequest]) (*connect.Response[v1.RegisterPINResponse], error) {
	return c.registerPIN.CallUnary(ctx, req)
}

// Unlock calls auth.v1.AuthService.Unlock.
func (c *authServiceClient) Unlock(ctx context.Context, req *connect.Request[v1.UnlockRequest]) (*connect.Response[v1.UnlockResponse], error) {
	return c.unlock.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.v1.AuthService service.
type AuthServiceHandler interface {
	SendOTP(context.Context, *connect.Request[v1.SendOTPRequest]) (*connect.Response[v1.SendOTPResponse], error)
	VerifyOTP(context.Context, *connect.Request[v1.VerifyOTPRequest]) (*connect.Response[v1.VerifyOTPResponse], error)
	RegisterPIN(context.Context, *connect.Request[v1.RegisterPINRequest]) (*connect.Response[v1.RegisterPINResponse], error)
	Unlock(context.Context, *connect.Request[v1.UnlockRequest]) (*connect.Response[v1.UnlockResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceSendOTPHandler := connect.NewUnaryHandler(
		AuthServiceSendOTPProcedure,
		svc.SendOTP,
		connect.WithSchema(authServiceSendOTPMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	authServiceVerifyOTPHandler := connect.NewUnaryHandler(
		AuthServiceVerifyOTPProcedure,
		svc.VerifyOTP,
		connect.WithSchema(authServiceVerifyOTPMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRegisterPINHandler := connect.NewUnaryHandler(
		AuthServiceRegisterPINProcedure,
		svc.RegisterPIN,
		connect.WithSchema(authServiceRegisterPINMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUnlockHandler := connect.NewUnaryHandler(
		AuthServiceUnlockProcedure,
		svc.Unlock,
		connect.WithSchema(authServiceUnlockMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceSendOTPProcedure:
			authServiceSendOTPHandler.ServeHTTP(w, r)
		case AuthServiceVerifyOTPProcedure:
			authServiceVerifyOTPHandler.ServeHTTP(w, r)
		case AuthServiceRegisterPINProcedure:
			authServiceRegisterPINHandler.ServeHTTP(w, r)
		case AuthServiceUnlockProcedure:
			authServiceUnlockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) SendOTP(context.Context, *connect.Request[v1.SendOTPRequest]) (*connect.Response[v1.SendOTPResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.SendOTP is not implemented"))
}

func (UnimplementedAuthServiceHandler) VerifyOTP(context.Context, *connect.Request[v1.VerifyOTPRequest]) (*connect.Response[v1.VerifyOTPResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.VerifyOTP is not implemented"))
}

func (UnimplementedAuthServiceHandler) RegisterPIN(context.Context, *connect.Request[v1.RegisterPINRequest]) (*connect.Response[v1.RegisterPINResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.RegisterPIN is not implemented"))
}

func (UnimplementedAuthServiceHandler) Unlock(context.Context, *connect.Request[v1.UnlockRequest]) (*connect.Response[v1.UnlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Unlock is not implemented"))
}
