// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: medeb/v1/user.proto

package protosv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "medeb.local/proto/medeb/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MedebServiceName is the fully-qualified name of the MedebService service.
	MedebServiceName = "protos.v1.MedebService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MedebServiceRegisterProcedure is the fully-qualified name of the MedebService's Register RPC.
	MedebServiceRegisterProcedure = "/protos.v1.MedebService/Register"
)

// MedebServiceClient is a client for the protos.v1.MedebService service.
type MedebServiceClient interface {
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
}

// NewMedebServiceClient constructs a client for the protos.v1.MedebService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMedebServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MedebServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	medebServiceMethods := v1.File_medeb_v1_user_proto.Services().ByName("MedebService").Methods()
	return &medebServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+MedebServiceRegisterProcedure,
			connect.WithSchema(medebServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
	}
}

// medebServiceClient implements MedebServiceClient.
type medebServiceClient struct {
	register *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
}

// Register calls protos.v1.MedebService.Register.
func (c *medebServiceClient) Register(ctx context.Context, req *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	response, err := c.register.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// MedebServiceHandler is an implementation of the protos.v1.MedebService service.
type MedebServiceHandler interface {
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
}

// NewMedebServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMedebServiceHandler(svc MedebServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	medebServiceMethods := v1.File_medeb_v1_user_proto.Services().ByName("MedebService").Methods()
	medebServiceRegisterHandler := connect.NewUnaryHandlerSimple(
		MedebServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(medebServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	return "/protos.v1.MedebService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MedebServiceRegisterProcedure:
			medebServiceRegisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMedebServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMedebServiceHandler struct{}

func (UnimplementedMedebServiceHandler) Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protos.v1.MedebService.Register is not implemented"))
}
