// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: medeb/v1/user.proto

package protosv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   uint64                 `protobuf:"varint,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_medeb_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medeb_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_medeb_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPhoneNumber() uint64 {
	if x != nil {
		return x.PhoneNumber
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_medeb_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medeb_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_medeb_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_medeb_v1_user_proto protoreflect.FileDescriptor

const file_medeb_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x13medeb/v1/user.proto\x12\tprotos.v1\x1a\x1bbuf/validate/validate.proto\"I\n" +
	"\x0fRegisterRequest\x126\n" +
	"\fphone_number\x18\x01 \x01(\x04B\x13\xbaH\x10\xc8\x01\x012\v\x18\xff\x93\xeb\xdc\x03(\x80\xc2\xd7/R\vphoneNumber\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2U\n" +
	"\fMedebService\x12E\n" +
	"\bRegister\x12\x1a.protos.v1.RegisterRequest\x1a\x1b.protos.v1.RegisterResponse\"\x00B\x94\x01\n" +
	"\rcom.protos.v1B\tUserProtoP\x01Z3github.com/kaleabAlemayehu/protos/medeb/v1;protosv1\xa2\x02\x03PXX\xaa\x02\tProtos.V1\xca\x02\tProtos\\V1\xe2\x02\x15Protos\\V1\\GPBMetadata\xea\x02\n" +
	"Protos::V1b\x06proto3"

var (
	file_medeb_v1_user_proto_rawDescOnce sync.Once
	file_medeb_v1_user_proto_rawDescData []byte
)

func file_medeb_v1_user_proto_rawDescGZIP() []byte {
	file_medeb_v1_user_proto_rawDescOnce.Do(func() {
		file_medeb_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medeb_v1_user_proto_rawDesc), len(file_medeb_v1_user_proto_rawDesc)))
	})
	return file_medeb_v1_user_proto_rawDescData
}

var file_medeb_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_medeb_v1_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: protos.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: protos.v1.RegisterResponse
}
var file_medeb_v1_user_proto_depIdxs = []int32{
	0, // 0: protos.v1.MedebService.Register:input_type -> protos.v1.RegisterRequest
	1, // 1: protos.v1.MedebService.Register:output_type -> protos.v1.RegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_medeb_v1_user_proto_init() }
func file_medeb_v1_user_proto_init() {
	if File_medeb_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medeb_v1_user_proto_rawDesc), len(file_medeb_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medeb_v1_user_proto_goTypes,
		DependencyIndexes: file_medeb_v1_user_proto_depIdxs,
		MessageInfos:      file_medeb_v1_user_proto_msgTypes,
	}.Build()
	File_medeb_v1_user_proto = out.File
	file_medeb_v1_user_proto_goTypes = nil
	file_medeb_v1_user_proto_depIdxs = nil
}
